### ISSUE TITLE
Running with IRON pythong for Raspberry PI2 image resulted in an error.

### ISSUE THREAD

**Issue by np83** [t0x0/random#4]
Hello,

I just tried running the script using the version from commit e667caf26523091952ab0fb756de072d2b962373

Some environment information:
Windows 8 with iron python 2.7
image to convert: Windows_IoT_Core_RPI2_BUILD

c:\Program Files (x86)\IronPython 2.7\ipy.exe" ffu2img.py Flash.FFU RPi.IMG
Input File: Flash.FFU
Output File: RPi.IMG
Block data entries begin: 0x600f8
Block data entries end: 0x79398
Block data chunks begin: 0x80000
6415 blocks, 821120kb written                                Traceback (most rec
ent call last):
  File "ffu2img.py", line 100, in <module>
  File "<string>", line 26, in _asdict
  File "c:\Program Files (x86)\IronPython 2.7\Lib\collections.py", line 51, in _
_init__
  File "c:\Program Files (x86)\IronPython 2.7\Lib\abc.py", line 151, in **subcla
sscheck**
  File "c:\Program Files (x86)\IronPython 2.7\Lib_weakrefset.py", line 73, in _
_contains__
SystemError: Handle is not initialized.

**Comment by t0x0** [comment]
Thank you for the information. Please try running with the official Python 2.7 or 3.4 package, available from https://www.python.org/downloads/windows/. I may look into why ffu2img is not compatible with IronPython, but since the official Python package doesn't error on Windows 8.1, Windows 10, Debian Wheezy or Fedora 22; it probably will not be in the immediate future.
